// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjynJZp6yeYHxTuQ7bBRM9OwaLK3PcZks',
    appId: '1:536787194899:android:85f4f23d0abb2cf0555be6',
    messagingSenderId: '536787194899',
    projectId: 'chat-app-8b210',
    storageBucket: 'chat-app-8b210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHOrzG7T3xEPzty40ImwNMwt86k75bxfg',
    appId: '1:536787194899:ios:31f7de8df7e50cfd555be6',
    messagingSenderId: '536787194899',
    projectId: 'chat-app-8b210',
    storageBucket: 'chat-app-8b210.appspot.com',
    iosClientId: '536787194899-0sh4uvlt63ehcgl5o57rrbng5uqrv24g.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHOrzG7T3xEPzty40ImwNMwt86k75bxfg',
    appId: '1:536787194899:ios:31f7de8df7e50cfd555be6',
    messagingSenderId: '536787194899',
    projectId: 'chat-app-8b210',
    storageBucket: 'chat-app-8b210.appspot.com',
    iosClientId: '536787194899-0sh4uvlt63ehcgl5o57rrbng5uqrv24g.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
